run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: tests/
      linters:
        - errcheck
    - path: _test\.go
      linters:
        - errcheck
